site_name: "Project Throne- Centralized Authentication Server"
repo_url: "https://github.com/kgrvamsi/throne"
site_author: "Vamsi KGR"
copyright: "2019, Vamsi KGR"
markdown_extensions: [fenced_code]
theme: "readthedocs"

pages:
- ['index.md', 'Home']